version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "80:80"
    volumes:
     - /srv/docker/phabricator/repos:/repos
     - /srv/docker/phabricator/extensions:/srv/phabricator/phabricator/src/extensions
    env_file:
     - variable.env
    image: redpointgames/phabricator